//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Cor3.Parsers {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Cor3.Parsers.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;!DOCUMENT !&gt;
		///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; dir=&quot;ltr&quot; lang=&quot;en-US&quot; xml:lang=&quot;en-US&quot;&gt;
		///	&lt;head&gt;
		///		&lt;BASE HREF=&quot;$(DocumentBase)&quot;&gt;&lt;!-- TARGET=&quot;WindowName&quot; --&gt;
		///		&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
		///		&lt;title&gt;$(DocumentTitle)&lt;/title&gt;$(StylesheetInclude)$(JavascriptInclude)$(StylesheetContent)
		///	&lt;/head&gt;
		///	&lt;body$(IsEditable)&gt;$(DocumentContent)$(JavascriptContent)
		///	&lt;/body&gt;
		///&lt;/html&gt;.
		/// </summary>
		public static string TemplateHtmlDocument {
			get {
				return ResourceManager.GetString("TemplateHtmlDocument", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///		&lt;script language=&apos;javascript&apos; type=&apos;text/javascript&apos;&gt;$(Include)&lt;/script&gt;.
		/// </summary>
		public static string TemplateJavascriptContentInclude {
			get {
				return ResourceManager.GetString("TemplateJavascriptContentInclude", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///		&lt;script src=&apos;$(Include)&apos; language=&apos;javascript&apos; type=&apos;text/javascript&apos;&gt;&lt;/script&gt;.
		/// </summary>
		public static string TemplateJavascriptInclude {
			get {
				return ResourceManager.GetString("TemplateJavascriptInclude", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///		&lt;style&gt;
		///html,body,span,div,p {
		///	font-family: ubuntu;
		///	font-size: 1em;
		///	line-height: 1;
		///}
		///p
		///{
		///	padding-top:	4pt;
		///	padding-bottom:	4pt;
		///}
		///		&lt;/style&gt;.
		/// </summary>
		public static string TemplateStyleSheetContent {
			get {
				return ResourceManager.GetString("TemplateStyleSheetContent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to 
		///		&lt;link rel=&apos;stylesheet&apos; href=&apos;$(Include)&apos; type=&apos;text/css&apos; /&gt;.
		/// </summary>
		public static string TemplateStyleSheetInclude {
			get {
				return ResourceManager.GetString("TemplateStyleSheetInclude", resourceCulture);
			}
		}
	}
}
